### ISSUE TITLE
To do list of modifications

### ISSUE THREAD

**Issue by Paul-Baudin** [stephenwhitmarsh/EpiCode#36]
I put here the to do list of the modifications we discussed today. I don't have time to do it now, but rather in a few weeks.

- create a function which finds samples overlapping with periods defined by Muse markers. The output trl could be then used with ft_rejectartifact. Much easier and more flexible than the current removetrials_MuseMarkers I use in dtx/to_share. However this solution will not work on spike data, as ft_rejectartifacts only works for 'raw' fieldtrip data and not 'spike' fieldtrip data. The issue with spike data is to not consider an artefacted period as a period where the neuron is silent. Maybe then, create our own function to re-cut the spike trials so there is no BAD samples in it. It would be better than removing the whole trial, as I am doing now with removetrials_MuseMarkers.
- readSpikeTrials_MuseMarkers : to rename readSpikeTrials. Add hypnogram stages in the trialinfo
- readSpikeWaveforms : add the trialinfo line of the original spike trial (so it will have the stage number). But it would be probably easier to directly read spike waveforms with ft_spiketriggeredaverage, keeptrials = 'yes'.
- spikeratestats_Events_Baseline : remove data to config and add it to varargin

Note that you need the function ft_spike_maketrials modified in /development/modified_fieldtrip_functions to separate into trials all the fields created by readSpikeRaw_Phy. Because some fields are new and not used previously by Fieldtrip.

Paul

**Comment by stephenwhitmarsh** [comment]
Thanks a lot for this, let's work through them together.

Op di 29 sep. 2020 om 19:39 schreef Paul-Baudin <notifications@github.com>:
