### ISSUE TITLE
artefact search with bsearch doesn't work with 1 artefact

### ISSUE THREAD

**Issue by stephenwhitmarsh** [stephenwhitmarsh/EpiCode#49]
In e.g. readSpikeTrials_MuseMarkers line 296; bsearch will return empty if there is one artefact.
@Paul-Baudin

**Comment by Paul-Baudin** [comment]
And also, I was finally not happy with it as I do not want to know if ***at least*** one artefact intersects the trial, but to know ***all*** artefacts intersecting the trial, to see if I can neglect them with their length, or not.
So maybe just remove this test in the script. The other strategy takes few minutes in my data, it is still fine.

**Comment by stephenwhitmarsh** [comment]
okay, since you added it, remove it and do a PR :)

**Comment by stephenwhitmarsh** [comment]
removed
