### ISSUE TITLE
Plotting trial-metrics on continuous time-axis

### ISSUE THREAD

**Issue by stephenwhitmarsh** [stephenwhitmarsh/EpiCode#62]
Issue: 
Multiple scripts over projects that plot spike-trial metrics over time with inflexible, redundant and un-validated code that depends on idiosyncratic (project-specific) organization of data.

Desired solution: 
Flexible high-level function on plotting trial metrics on common time-axis.
- Input data should be organized in (overlapping) epochs (trials), with either/or real "clock" time, or seconds (from file onset), with the same time reference. This is now done 'manually' by creating (overlapping) 'MuseMarkers' of a certain duration (markername = "window"), but will be done in a function (#61), after which the new MuseStruct can be used by  [readSpikeTrials_MuseMarkers](https://github.com/stephenwhitmarsh/EpiCode/blob/bda234d4d0406a1e2bec0de3b4f6673e50829ec7/shared/readSpikeTrials_MuseMarkers.m) to create the epochs.
- All metric calculated subsequently by [spikeTrialStats](https://github.com/stephenwhitmarsh/EpiCode/blob/bda234d4d0406a1e2bec0de3b4f6673e50829ec7/shared/spikeTrialStats.m) should be possible to plot, and vice-versa everything that is plotted should be calculated in spikeTrialStats. See e.g. recent addition of Spiky calculations.
- All selected metrics are plotted vertically as figure-wide rows with common time axis.
- Common time axis can be one of the following: samples from file onset, time from file onset, "clock" time.
- Common time axis can be rereferenced by (relative to) a single event (e.g. seizure) given as an additional configuration input.
- Metrics are plotted optionally as a single line (e.g. FR), multiple lines (e.g. connectivity) or bar (with bar width expressed in common time axis).
- Intervals, e.g. artefacts, seizures, can be plotted as shaded areas.
- Markers can be added to each time-point as a symbol indicated by a boolean value (e.g. artefacted: true/false, IED present: true/false).
- Time-axis range can be indicated (i.e. zoom in to a specific period).
- Which values are plotted (in figure-wide subplots) are selected simply by the fieldname in the [spikeTrialStats](https://github.com/stephenwhitmarsh/EpiCode/blob/bda234d4d0406a1e2bec0de3b4f6673e50829ec7/shared/spikeTrialStats.m) output (e.g.: `cfg.plot.stat = {"FR", "CV2", "distance"}`)
- Option to add the hypnogram (trial-based, not in the original timing anymore, so consistent with the rest).

**Comment by stephenwhitmarsh** [comment]
add option to plot multiple units at the same time

**Comment by Antho2422** [comment]
Suggested to draw marker timings as lines in plots, e.g. type = 'marker'
